### ISSUE TITLE
"moment_1.default.locale" is not a function

### ISSUE THREAD

**Issue by snowbagoly** [zheyujie/semantic-ui-calendar-react#2]
First of all, thank you for maintaining this project!

I have bumped into the issue that we cannot use the library with our configuration as it throws this error in the browser for the BaseInput.js, when I add a DateInput:

```
moment_1.default.locale is not a function
```

I've found that the problem might be with the moment version, I've set it to 2.24.0 explicitly, but it didn't solve the problem. I've also seen in [this thread](https://github.com/aurelia/skeleton-navigation/issues/606) that the settings

```
"esModuleInterop": true,
"allowSyntheticDefaultImports": true
```
in the `tsconfig.json` might help, but no luck. We are using TypeScript v4.3.2. Have you maybe encountered this issue?

**Comment by zheyujie** [comment]
Hi @snowbagoly, I've not encountered this problem before...
The tsconfig for this library already has `allowSyntheticDefaultImports` set to true.

Have you tried pulling this library, change the way it imports moment to `import * as moment from 'moment'` and see if it helps?
You should be able to use npm link or yarn link to link this library to your project locally to test it.
